apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rogue-paprika-top-tls
spec:
  secretName: rogue-paprika-top
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rogue-paprika.top
  dnsNames:
    - rogue-paprika.top
    - www.rogue-paprika.top